compatibility_date = "2022-01-28"
name = "tiny-frontent-api-cloudlare-example"

kv_namespaces = [
    { binding = "TinyFrontendKv", id = "7113fb20c2464dcc9c521f8b0bb4d45e", preview_id = "81443b04b2c543f6bcd8305d23d3bf6c" }
]
